package org.juns.marketboardbackend.screener.dto;

public enum ScreenerSortField {
    MOMENTUM_3M, MOMENTUM_6M, MOMENTUM_12M, RSI_14, VOLATILITY_20D,
    EMA_20, MACD_HISTOGRAM, BOLLINGER_PERCENT_B_20, ATR_PCT_14, RELATIVE_VOLUME_20,
    MARKET_CAP, REVENUE_GROWTH, ROE, TRAILING_PE, NEWS_SENTIMENT, TICKER
}
